# Paleta de Cores BLUE para o AiNOMEATOR
[Cores]
vocal_principal = #00A2E8
backing_vocals = #99D9EA
bateria = #0F4C81
percussao = #4A86E8
baixo = #192D73
guitarra_eletrica = #3264B4
violao = #78A0DC
teclado = #64B4DC
synth = #A0D2F0
cordas = #5A78A0
sopros = #8CB4E6
efeitos = #7882A0
pastas = #323746
outro = #828796
