# Paleta de Cores RED para o AiNOMEATOR
[Cores]
vocal_principal = #DC143C
backing_vocals = #F08080
bateria = #8B0000
percussao = #CD5C5C
baixo = #500A0A
guitarra_eletrica = #B42828
violao = #D26464
teclado = #E68C64
synth = #FFB496
cordas = #A03C3C
sopros = #C85078
efeitos = #967878
pastas = #412D2D
outro = #8C7D7D
